# Utiliza una imagen base oficial de Node.js
FROM node:16-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la aplicación a /app
COPY package*.json ./

# Instala las dependencias de Node.js
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto que la aplicación usará
EXPOSE 3000

# Define el comando por defecto para ejecutar la aplicación
CMD ["npm", "run", "dev"]
